root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ."

bin = "fmp/main"

full_bin = "APP_ENV=dev APP_USER=air ./tmp/main 80"

include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assetes", "tmp", "vendor"]
include_dir = []
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = true
follw_symlink = true
log = "air.log"
delay = 1000
stop_on_error = true
send_interput = false
kill_deploy = 500

[log]
time = false

[color]
main = "magenta"
watcher = "cyon"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true